
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 12 10:00:34 CET 2013
//----------------------------------------------------

package calculator;

/** CUP generated interface containing symbol constants. */
public interface CalculatorSym {
  /* terminals */
  public static final int MIB = 15;
  public static final int DOD = 11;
  public static final int SILENCE = 27;
  public static final int BPM = 3;
  public static final int SOL = 20;
  public static final int PLAY = 8;
  public static final int END = 6;
  public static final int SIB = 25;
  public static final int FAD = 18;
  public static final int RED = 14;
  public static final int ID = 9;
  public static final int FA = 17;
  public static final int REB = 12;
  public static final int RE = 13;
  public static final int BEGIN = 5;
  public static final int DO = 10;
  public static final int LA = 23;
  public static final int SOLD = 21;
  public static final int SOLB = 19;
  public static final int COMMA = 7;
  public static final int EOF = 0;
  public static final int DURATION = 2;
  public static final int MI = 16;
  public static final int SI = 26;
  public static final int LAD = 24;
  public static final int error = 1;
  public static final int LAB = 22;
  public static final int TERM = 4;
}

