
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 05 11:20:59 CET 2014
//----------------------------------------------------

package calculator;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int MIB = 14;
  public static final int DOD = 10;
  public static final int SILENCE = 26;
  public static final int BPM = 3;
  public static final int SOL = 19;
  public static final int PLAY = 7;
  public static final int END = 5;
  public static final int SIB = 24;
  public static final int FAD = 17;
  public static final int RED = 13;
  public static final int ID = 8;
  public static final int FA = 16;
  public static final int RE = 12;
  public static final int REB = 11;
  public static final int DO = 9;
  public static final int BEGIN = 4;
  public static final int LA = 22;
  public static final int SOLD = 20;
  public static final int SOLB = 18;
  public static final int COMMA = 6;
  public static final int EOF = 0;
  public static final int DURATION = 2;
  public static final int MI = 15;
  public static final int SI = 25;
  public static final int LAD = 23;
  public static final int error = 1;
  public static final int LAB = 21;
}

